# Generated by Django 4.0.4 on 2022-05-11 12:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('qty', models.CharField(max_length=120)),
                ('unit', models.CharField(max_length=120)),
                ('food', models.CharField(max_length=120)),
                ('calories', models.CharField(max_length=120)),
                ('weight', models.CharField(max_length=120)),
                ('phosphorus', models.CharField(max_length=120)),
                ('potassium', models.CharField(max_length=120)),
                ('energy', models.CharField(max_length=120)),
                ('iron', models.CharField(max_length=120)),
                ('sodium', models.CharField(max_length=120)),
                ('glucose', models.CharField(max_length=120)),
                ('carbohydrates', models.CharField(max_length=120)),
                ('calcium', models.CharField(max_length=120)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('exercise', models.CharField(max_length=120)),
                ('duration', models.CharField(max_length=60)),
                ('calories', models.CharField(max_length=120)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
