# Generated by Django 4.0.4 on 2022-05-11 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livfit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='fats',
            field=models.CharField(default=0, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='food',
            name='fiber',
            field=models.CharField(default=0, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='food',
            name='protein',
            field=models.CharField(default=0, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='food',
            name='sugar',
            field=models.CharField(default=0, max_length=120),
            preserve_default=False,
        ),
    ]
